#!/bin/sh

trap print_exit INT
trap print_on_kill KILL

print_exit() {
	echo " I  have been interrupted!"
	exit
}

echo "I am gonna sleep for many many seconds now..."
sleep 500

echo "I will be back!"
